### ISSUE TITLE
TODO for MVP

### ISSUE THREAD

**Issue by jamohile** [googleinterns/step86-2020#19]
These are only features needed before MVP can be marked complete. This doesn't include anything that is part of Milestone 2+.

**Critical**
- [x] Replace mock functions with calls to BackgroundRequest methods in chathead
- [x] Basic UI and logic for displaying breakpoint (**only one for now**)
 - Could even use polling to keep things simple

**Nice to have, but not blockers**
- [ ] Collapsible or movable chathead
- [ ] Add detailed typescript definitions for Project, Breakpoint, etc.
